development:
  adapter: mysql2
  database: meli_listing_updates_notifier_dev
  username: root
  password:
  host: localhost
  pool: 5
  timeout: 5000
  encoding: utf8

test:
  adapter: mysql2
  database: meli_listing_updates_notifier_test
  username: root
  password:
  host: localhost
  pool: 5
  timeout: 5000
  encoding: utf8
